# Generated by Django 4.2.14 on 2024-07-18 19:57

from django.db import migrations

from learning_resources.utils import upsert_topic_data_file


def perform_topic_upsert(apps, schema_editor):
    """Upsert the topic data from the default location."""

    upsert_topic_data_file()


def perform_topic_unupsert(apps, schema_editor):
    """Do nothing (this is just to make the migration reversable)."""


class Migration(migrations.Migration):
    """Insert the topic data from the topics.yaml file."""

    dependencies = [
        ("data_fixtures", "0003_unit_page_copy_updates"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    "TRUNCATE learning_resources_learningresourcetopic "
                    "RESTART IDENTITY CASCADE"
                )
            ],
            reverse_sql="",
        ),
        migrations.RunPython(perform_topic_upsert, perform_topic_unupsert),
    ]
