# Generated by Django 4.2.14 on 2024-08-06 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_fixtures",
            "0007_topic_mappings_edx_add_programming_coding_to_computer_science",
        ),
    ]

    operations = []
