# Generated by Django 4.2.11 on 2024-05-07 21:28

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('computer-science', 'Computer Science'), ('business', 'Business'), ('engineering', 'Engineering'), ('leadership', 'Leadership'), ('organized-behavior', 'Organized Behavior'), ('management', 'Management'), ('electrical-engineering', 'Electrical Engineering'), ('information-technology', 'Information Technology'), ('biology', 'Biology'), ('earth-science', 'Earth Science'), ('environmental-engineering', 'Environmental Engineering'), ('health-and-medicine', 'Health & Medicine'), ('probability-and-stats', 'Probability & Stats'), ('economics', 'Economics'), ('history', 'History'), ('mathematics', 'Mathematics'), ('mechanical-engineering', 'Mechanical Engineering'), ('other', 'Other')], max_length=50), size=None)),
                ('goals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('career-growth', 'Career Growth'), ('supplemental-learning', 'Supplemental Learning'), ('just-to-learn', 'Just to Learn')], max_length=50), size=None)),
                ('certificate_desired', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not-sure-yet', 'Not Sure Yet')], max_length=50)),
                ('current_education', models.CharField(choices=[('no-formal', 'No Formal Education'), ('primary', 'Primary Education'), ('secondary-or-high-school', 'Secondary Education or High School'), ('ged', 'GED'), ('vocational-qualification', 'Vocational Qualification')], max_length=50)),
                ('time_commitment', models.CharField(choices=[('0-to-5-hours', '<5 hours/week'), ('5-to-10-hours', '5-10 hours/week'), ('10-to-20-hours', '10-20 hours/week'), ('20-to-30-hours', '20-30 hours/week'), ('30-plus-hours', '30+ hours/week')], max_length=50)),
                ('course_format', models.CharField(choices=[('online', 'Online'), ('in-person', 'In-Person'), ('hybrid', 'Hybrid')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
