# Generated by Django 4.2.9 on 2024-02-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_alter_profile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="scim_external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="A string that is an identifier for the resource as defined by the provisioning client.",  # noqa: E501
                max_length=254,
                null=True,
                verbose_name="SCIM External ID",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="scim_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="A unique identifier for a SCIM resource as defined by the service provider.",  # noqa: E501
                max_length=254,
                null=True,
                unique=True,
                verbose_name="SCIM ID",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="scim_username",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="A service provider's unique identifier for the user",
                max_length=254,
                null=True,
                verbose_name="SCIM Username",
            ),
        ),
    ]
