# Generated by Django 4.2.9 on 2024-02-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_profile_scim_external_id_profile_scim_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
