# Generated by Django 4.2.10 on 2024-02-28 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0015_programcertificate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programcertificate",
            options={"managed": False},
        ),
    ]
