# Generated by Django 4.2.10 on 2024-03-05 20:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_programcertificate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.programcertificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
