# Generated by Django 4.2.11 on 2024-04-01 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0019_alter_programcertificate_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programcertificate",
            options={"managed": True},
        ),
    ]
