# Generated by Django 4.2.11 on 2024-04-01 20:49

import uuid

from django.db import migrations, models, transaction


def gen_uuid(apps, schema_editor):
    ProgramCertificate = apps.get_model("profiles", "ProgramCertificate")
    while ProgramCertificate.objects.filter(record_hash__isnull=True).exists():
        with transaction.atomic():
            for row in ProgramCertificate.objects.filter(record_hash__isnull=True):
                row.record_hash = uuid.uuid4()
                row.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0021_programcertificate_record_hash"),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
        migrations.AlterField(
            model_name="programcertificate",
            name="record_hash",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterModelOptions(
            name="programcertificate",
            options={"managed": False},
        ),
    ]
