# Generated by Django 4.2.11 on 2024-04-01 20:49

import uuid

from django.conf import settings
from django.db import migrations, models, transaction


def generate_program_certificate_uuid(apps, schema_editor):
    ProgramCertificate = apps.get_model("profiles", "ProgramCertificate")
    while ProgramCertificate.objects.filter(record_hash__isnull=True).exists():
        with transaction.atomic():
            external = list(settings.EXTERNAL_MODELS)
            settings.EXTERNAL_MODELS = []
            for row in ProgramCertificate.objects.filter(record_hash__isnull=True):
                row.record_hash = str(uuid.uuid4())
                row.save()
        settings.EXTERNAL_MODELS = external


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0021_programcertificate_record_hash"),
    ]
    operations = [
        migrations.RunPython(generate_program_certificate_uuid),
        migrations.RemoveField(
            model_name="programcertificate",
            name="id",
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="record_hash",
            field=models.CharField(
                editable=False,
                max_length=256,
                primary_key=True,
                null=False,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterModelOptions(
            name="programcertificate",
            options={"managed": False},
        ),
    ]
