# Generated by Django 4.2.11 on 2024-04-10 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0022_fill_programcertificate_record_hash"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE profiles_programletter ALTER certificate_id TYPE varchar(256);"
        ),
    ]
