# Generated by Django 4.2.11 on 2024-04-11 16:12

from django.db import migrations, models

import profiles.models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0023_fix_program_certificate_foreign_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programcertificate",
            options={"managed": True},
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="record_hash",
            field=models.CharField(
                default=profiles.models.certificate_id,
                editable=False,
                max_length=256,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="user_address_city",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="user_address_postal_code",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="user_address_state_or_territory",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="user_country",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="user_edxorg_username",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="user_first_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="user_gender",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="user_last_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="user_mitxonline_username",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="user_street_address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="user_year_of_birth",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterModelOptions(
            name="programcertificate",
            options={"managed": False},
        ),
    ]
