# Generated by Django 4.2.13 on 2024-05-20 21:03

import django.contrib.postgres.fields
from django.db import migrations, models

import profiles.utils


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0024_alter_programcertificate_record_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="certificate_desired",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("not-sure-yet", "Not Sure Yet"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="course_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online", "Online"),
                    ("in-person", "In-Person"),
                    ("hybrid", "Hybrid"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="current_education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no-formal", "No Formal Education"),
                    ("primary", "Primary Education"),
                    ("secondary-or-high-school", "Secondary Education or High School"),
                    ("ged", "GED"),
                    ("vocational-qualification", "Vocational Qualification"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="goals",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("career-growth", "Career Growth"),
                        ("supplemental-learning", "Supplemental Learning"),
                        ("just-to-learn", "Just to Learn"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("computer-science", "Computer Science"),
                        ("business", "Business"),
                        ("engineering", "Engineering"),
                        ("leadership", "Leadership"),
                        ("organized-behavior", "Organized Behavior"),
                        ("management", "Management"),
                        ("electrical-engineering", "Electrical Engineering"),
                        ("information-technology", "Information Technology"),
                        ("biology", "Biology"),
                        ("earth-science", "Earth Science"),
                        ("environmental-engineering", "Environmental Engineering"),
                        ("health-and-medicine", "Health & Medicine"),
                        ("probability-and-stats", "Probability & Stats"),
                        ("economics", "Economics"),
                        ("history", "History"),
                        ("mathematics", "Mathematics"),
                        ("mechanical-engineering", "Mechanical Engineering"),
                        ("other", "Other"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="time_commitment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-to-5-hours", "<5 hours/week"),
                    ("5-to-10-hours", "5-10 hours/week"),
                    ("10-to-20-hours", "10-20 hours/week"),
                    ("20-to-30-hours", "20-30 hours/week"),
                    ("30-plus-hours", "30+ hours/week"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image_file",
            field=models.ImageField(
                editable=False,
                max_length=2083,
                null=True,
                upload_to=profiles.utils.profile_image_upload_uri,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image_medium_file",
            field=models.ImageField(
                editable=False,
                max_length=2083,
                null=True,
                upload_to=profiles.utils.profile_image_upload_uri_medium,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image_small_file",
            field=models.ImageField(
                editable=False,
                max_length=2083,
                null=True,
                upload_to=profiles.utils.profile_image_upload_uri_small,
            ),
        ),
    ]
