# Generated by Django 4.2.13 on 2024-06-12 13:53

from django.db import migrations, models


def set_profile_education_blank(apps, schema_editor):
    """Apply the migration"""
    Profile = apps.get_model("profiles", "Profile")

    Profile.objects.update(current_education="")


class Migration(migrations.Migration):
    """
    Empty out the Profile.current_education field on all profiles
    since we changed the options completely.
    """

    dependencies = [
        ("profiles", "0026_onboarding_lr_fields"),
    ]

    operations = [
        migrations.RunPython(set_profile_education_blank),
        migrations.AlterField(
            model_name="profile",
            name="current_education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----"),
                    ("Doctorate", "Doctorate"),
                    (
                        "Master's or professional degree",
                        "Master's or professional degree",
                    ),
                    ("Bachelor's degree", "Bachelor's degree"),
                    ("Associate degree", "Associate degree"),
                    ("Secondary/high school", "Secondary/high school"),
                    (
                        "Junior secondary/junior high/middle school",
                        "Junior secondary/junior high/middle school",
                    ),
                    ("Elementary/primary school", "Elementary/primary school"),
                    ("No formal education", "No formal education"),
                    ("Other education", "Other education"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
