# Generated by Django 4.2.14 on 2024-07-12 19:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0027_update_profile_education_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="goals",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("academic-excellence", "Academic Excellence"),
                        ("career-growth", "Career Growth"),
                        ("lifelong-learning", "Lifelong Learning"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
