# Generated by Django 4.2.14 on 2024-07-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0028_alter_profile_goals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="certificate_desired",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes, I am looking for a certificate"),
                    ("no", "No, I am not looking for a certificate"),
                    ("not-sure-yet", "Not Sure"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
