# Generated by Django 4.2.14 on 2024-07-12 22:17

import django.contrib.postgres.fields
from django.db import migrations, models


def reset_learning_format(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    Profile.objects.all().update(learning_format={})


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0029_alter_profile_certificate_desired"),
    ]

    operations = [
        migrations.RunPython(reset_learning_format),
        migrations.AlterField(
            model_name="profile",
            name="learning_format",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("online", "Online"),
                        ("hybrid", "Hybrid"),
                        ("in_person", "In-Person"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
