# Generated by Django 4.2.14 on 2024-07-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0030_alter_profile_learning_format"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email_optin",
        ),
        migrations.AddField(
            model_name="profile",
            name="notification_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never/Unsubscribe"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                ],
                default="daily",
                max_length=50,
            ),
        ),
    ]
