# Generated by Django 4.2.14 on 2024-07-17 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0031_profile_notification_preference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email_optin",
        ),
    ]
