# Generated by Django 4.2.16 on 2024-09-16 17:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0032_alter_profile_current_education"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="learning_format",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("online", "Online"),
                        ("hybrid", "Hybrid"),
                        ("in_person", "In-Person"),
                        ("offline", "Offline"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="learning_format",
            new_name="delivery",
        ),
    ]
