extends:
  - stylelint-config-standard
rules:
  selector-class-pattern:
    - (^ck.*)|((^Mui[A-Z-])|^([a-z][a-z0-9]*)((-|__?)[a-z0-9]+)*$) # CKEditor, MUI or kebab-case
    - message: "Expected class selector to be kebab-case"
ignoreFiles:
  - "**/*.vendor.css"
overrides:
  - files:
      - "**/*.scss"
    extends:
      - stylelint-config-standard-scss
  - files:
      - "**/*.tsx"
      - "**/*.ts"
    customSyntax: postcss-styled-syntax
