include:
  - docker-compose.services.yml

services:
  web:
    extends:
      file: docker-compose.apps.yml
      service: web
    env_file:
      - path: env/shared.env
      - path: env/shared.local.env
        required: false
      - path: env/backend.env
      - path: env/backend.local.env
        required: false
      # DEPRECATED: legacy .env file at the repo root
      - path: .env
        required: false

  watch:
    extends:
      file: docker-compose.apps.yml
      service: watch
    env_file:
      - path: env/shared.env
      - path: env/shared.local.env
        required: false
      - path: env/frontend.env
      - path: env/frontend.local.env
        required: false
      # DEPRECATED: legacy .env file at the repo root
      - path: .env
        required: false

  celery:
    extends:
      file: docker-compose.apps.yml
      service: celery
    env_file:
      - path: env/shared.env
      - path: env/shared.local.env
        required: false
      - path: env/backend.env
      - path: env/backend.local.env
        required: false
      # DEPRECATED: legacy .env file at the repo root
      - path: .env
        required: false
    environment:
      REMAP_SIGTERM: SIGQUIT
