include:
  - docker-compose.services.yml

services:
  web:
    extends:
      file: docker-compose.apps.yml
      service: web
    env_file: env/codespaces.env

  watch:
    extends:
      file: docker-compose.apps.yml
      service: watch
    env_file: env/codespaces.env

  celery:
    extends:
      file: docker-compose.apps.yml
      service: celery
    env_file: env/codespaces.env

  opensearch-node-mitopen-1:
    extends:
      file: docker-compose.opensearch.base.yml
      service: opensearch
    hostname: opensearch-node-mitopen-1
    environment:
      - "node.name=opensearch-node-mitopen-1"
      - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9100:9200 # REST API
      - 9500:9600 # Performance Analyzer

volumes:
  opensearch-data1:
