include:
  - docker-compose.opensearch.${OPENSEARCH_CLUSTER_TYPE:-single-node}.yml

services:
  web:
    profiles:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    extends:
      file: docker-compose.opensearch.${OPENSEARCH_CLUSTER_TYPE:-single-node}.apps.yml
      service: web
    mem_limit: 1gb
    cpus: 2
    command: ./scripts/run-django-dev.sh
    stdin_open: true
    tty: true
    ports:
      - "8061:8061"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/src
      - django_media:/var/media

  watch:
    profiles:
      - frontend
    working_dir: /src
    image: node:20.17
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        yarn install --immutable
        yarn workspace ol-components storybook --no-open &
        yarn watch
    ports:
      - "8062:8062"
      - "6006:6006"
    environment:
      - NEXT_SERVER_MITOL_API_BASE_URL=http://nginx:8063/
    volumes:
      - .:/src
    links:
      - web

  celery:
    profiles:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    extends:
      file: docker-compose.opensearch.${OPENSEARCH_CLUSTER_TYPE:-single-node}.apps.yml
      service: web
    command: >
      /bin/bash -c '
      sleep 3;
      celery -A main.celery:app worker -Q default -B -l ${MITOL_LOG_LEVEL:-INFO} &
      celery -A main.celery:app worker -Q edx_content,default -l ${MITOL_LOG_LEVEL:-INFO}'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/src
      - django_media:/var/media
