version: "3.7"

x-environment: &py-environment
  DEBUG: ${DEBUG:-True}
  DEV_ENV: "True" # necessary to have nginx connect to web container
  NODE_ENV: ${NODE_ENV:-development}
  DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
  MITOPEN_SECURE_SSL_REDIRECT: "False"
  MITOPEN_DB_DISABLE_SSL: "True"
  MITOPEN_FEATURES_DEFAULT: ${MITOPEN_FEATURES_DEFAULT:-True}
  OPENSEARCH_URL: opensearch-node-mitopen:9200
  CELERY_TASK_ALWAYS_EAGER: "False"
  CELERY_BROKER_URL: redis://redis:6379/4
  CELERY_RESULT_BACKEND: redis://redis:6379/4
  DOCKER_HOST: ${DOCKER_HOST:-missing}

  TIKA_SERVER_ENDPOINT: ${TIKA_SERVER_ENDPOINT:-http://tika:9998/}
  TIKA_CLIENT_ONLY: "True"

services:
  db:
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:5.0.14
    ports:
      - "6379"

  opensearch-node-mitopen:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-node-mitopen
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node-mitopen
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9100:9200

  nginx:
    image: nginx:1.25.3
    ports:
      - "8063:8063"
    links:
      - web
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/web.conf
      - ./:/src

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *py-environment
      PORT: 8061
    env_file: .env
    command: ./scripts/run-django-dev.sh
    stdin_open: true
    tty: true
    ports:
      - "8061:8061"
    links:
      - db
      - opensearch-node-mitopen
      - redis
      - watch
    volumes:
      - .:/src
      - django_media:/var/media

  watch:
    build:
      context: .
      dockerfile: Dockerfile-node
    working_dir: /src
    command: ./scripts/run-watch-dev.sh
    ports:
      - "8052:8052"
      - "8062:8062"
      - "6006:6006"
    environment:
      DOCKER_HOST: ${DOCKER_HOST:-missing}
      NODE_ENV: ${NODE_ENV:-development}
      CONTAINER_NAME: "watch"
      WEBPACK_PORT_MITOPEN: 8062
    env_file: .env
    volumes:
      - .:/src
      - yarn-cache:/home/mitodl/.cache/yarn

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    environment: *py-environment
    env_file: .env
    command: >
      /bin/bash -c '
      sleep 3;
      celery -A open_discussions.celery:app worker -Q default -B -l ${MITOPEN_LOG_LEVEL:-INFO} &
      celery -A open_discussions.celery:app worker -Q edx_content,default -l ${MITOPEN_LOG_LEVEL:-INFO}'
    links:
      - db
      - opensearch-node-mitopen
      - redis
    volumes:
      - .:/src
      - django_media:/var/media
  tika:
    image: apache/tika:1.28
    ports:
      - "9998:9998"

volumes:
  opensearch-data1:
  django_media:
  yarn-cache:
