include:
  - docker-compose.opensearch.${OPENSEARCH_CLUSTER_TYPE:-single-node}.yml

services:
  web:
    profiles:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 1gb
    cpus: 2
    command: ./scripts/run-django-dev.sh
    stdin_open: true
    tty: true
    ports:
      - "8061:8061"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/src
      - django_media:/var/media

  watch:
    profiles:
      - frontend
    working_dir: /src
    image: node:20.17
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        yarn install --immutable
        yarn workspace mit-learn storybook --no-open &
        yarn workspace mit-learn watch:docker
    ports:
      - "8062:8062"
      - "6006:6006"
    volumes:
      - .:/src

  celery:
    profiles:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/bash -c '
      sleep 3;
      celery -A main.celery:app worker -E -Q edx_content,default -l ${MITOL_LOG_LEVEL:-INFO}'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/src
      - django_media:/var/media
    environment:
      REMAP_SIGTERM: SIGQUIT
