openapi: 3.0.3
info:
  title: MIT Open Discussions Course Catalog API
  version: 0.0.1
  description: Open Discussions public API
paths:
  /api/v1/courses/:
    get:
      operationId: courses_list
      description: Get a paginated list of learning resources.
      summary: List
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - courses
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLearningResourceList'
          description: ''
  /api/v1/courses/{id}/:
    get:
      operationId: courses_retrieve
      description: Retrieve a single learning resource.
      summary: Retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this learning resource.
        required: true
      tags:
      - courses
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningResource'
          description: ''
  /api/v1/courses/new/:
    get:
      operationId: courses_new_list
      description: Get a paginated list of newly released resources.
      summary: List New
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - courses
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLearningResourceList'
          description: ''
  /api/v1/courses/upcoming/:
    get:
      operationId: courses_upcoming_list
      description: Get a paginated list of upcoming resources.
      summary: List Upcoming
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - courses
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLearningResourceList'
          description: ''
  /api/v1/learning_resources/:
    get:
      operationId: learning_resources_list
      description: Get a paginated list of learning resources.
      summary: List
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - learning_resources
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLearningResourceList'
          description: ''
  /api/v1/learning_resources/{id}/:
    get:
      operationId: learning_resources_retrieve
      description: Retrieve a single learning resource.
      summary: Retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this learning resource.
        required: true
      tags:
      - learning_resources
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningResource'
          description: ''
  /api/v1/learning_resources/new/:
    get:
      operationId: learning_resources_new_list
      description: Get a paginated list of newly released resources.
      summary: List New
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - learning_resources
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLearningResourceList'
          description: ''
  /api/v1/learning_resources/upcoming/:
    get:
      operationId: learning_resources_upcoming_list
      description: Get a paginated list of upcoming resources.
      summary: List Upcoming
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - learning_resources
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLearningResourceList'
          description: ''
  /api/v1/programs/:
    get:
      operationId: programs_list
      description: Get a paginated list of learning resources.
      summary: List
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - programs
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLearningResourceList'
          description: ''
  /api/v1/programs/{id}/:
    get:
      operationId: programs_retrieve
      description: Retrieve a single learning resource.
      summary: Retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this learning resource.
        required: true
      tags:
      - programs
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningResource'
          description: ''
  /api/v1/programs/new/:
    get:
      operationId: programs_new_list
      description: Get a paginated list of newly released resources.
      summary: List New
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - programs
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLearningResourceList'
          description: ''
  /api/v1/programs/upcoming/:
    get:
      operationId: programs_upcoming_list
      description: Get a paginated list of upcoming resources.
      summary: List Upcoming
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - programs
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLearningResourceList'
          description: ''
components:
  schemas:
    Course:
      type: object
      description: Serializer for the Course model
      properties:
        extra_course_numbers:
          type: array
          items:
            type: string
            maxLength: 128
          nullable: true
    LearningResource:
      type: object
      description: Full serializer for LearningResource
      properties:
        id:
          type: integer
          readOnly: true
        topics:
          type: array
          items:
            $ref: '#/components/schemas/LearningResourceTopic'
          readOnly: true
          nullable: true
        offered_by:
          type: array
          items:
            type: string
          readOnly: true
          nullable: true
        resource_content_tags:
          type: array
          items:
            type: string
          readOnly: true
          nullable: true
        image:
          allOf:
          - $ref: '#/components/schemas/LearningResourceImage'
          readOnly: true
          nullable: true
        department:
          allOf:
          - $ref: '#/components/schemas/LearningResourceDepartment'
          readOnly: true
          nullable: true
        audience:
          type: string
          nullable: true
          description: Returns the audience for the learning resource
          readOnly: true
        certification:
          type: string
          nullable: true
          description: Returns the certification for the learning resource
          readOnly: true
        prices:
          type: string
          nullable: true
          description: Returns the prices for the learning resource
          readOnly: true
        course:
          allOf:
          - $ref: '#/components/schemas/Course'
          readOnly: true
          nullable: true
        program:
          allOf:
          - $ref: '#/components/schemas/Program'
          readOnly: true
          nullable: true
        runs:
          type: array
          items:
            $ref: '#/components/schemas/LearningResourceRun'
          readOnly: true
          nullable: true
        readable_id:
          type: string
          maxLength: 128
        title:
          type: string
          maxLength: 256
        description:
          type: string
          nullable: true
        full_description:
          type: string
          nullable: true
        last_modified:
          type: string
          format: date-time
          nullable: true
        published:
          type: boolean
        languages:
          type: array
          items:
            type: string
            maxLength: 24
          nullable: true
        url:
          type: string
          format: uri
          nullable: true
          maxLength: 2048
        resource_type:
          type: string
          maxLength: 24
        platform:
          type: string
          nullable: true
      required:
      - audience
      - certification
      - course
      - department
      - id
      - image
      - offered_by
      - platform
      - prices
      - program
      - readable_id
      - resource_content_tags
      - resource_type
      - runs
      - title
      - topics
    LearningResourceBase:
      type: object
      description: Serializer for LearningResource, minus program, course
      properties:
        id:
          type: integer
          readOnly: true
        topics:
          type: array
          items:
            $ref: '#/components/schemas/LearningResourceTopic'
          readOnly: true
          nullable: true
        offered_by:
          type: array
          items:
            type: string
          readOnly: true
          nullable: true
        resource_content_tags:
          type: array
          items:
            type: string
          readOnly: true
          nullable: true
        image:
          allOf:
          - $ref: '#/components/schemas/LearningResourceImage'
          readOnly: true
          nullable: true
        department:
          allOf:
          - $ref: '#/components/schemas/LearningResourceDepartment'
          readOnly: true
          nullable: true
        audience:
          type: string
          nullable: true
          description: Returns the audience for the learning resource
          readOnly: true
        certification:
          type: string
          nullable: true
          description: Returns the certification for the learning resource
          readOnly: true
        prices:
          type: string
          nullable: true
          description: Returns the prices for the learning resource
          readOnly: true
        created_on:
          type: string
          format: date-time
          readOnly: true
        updated_on:
          type: string
          format: date-time
          readOnly: true
        readable_id:
          type: string
          maxLength: 128
        title:
          type: string
          maxLength: 256
        description:
          type: string
          nullable: true
        full_description:
          type: string
          nullable: true
        last_modified:
          type: string
          format: date-time
          nullable: true
        published:
          type: boolean
        languages:
          type: array
          items:
            type: string
            maxLength: 24
          nullable: true
        url:
          type: string
          format: uri
          nullable: true
          maxLength: 2048
        resource_type:
          type: string
          maxLength: 24
        platform:
          type: string
          nullable: true
      required:
      - audience
      - certification
      - created_on
      - department
      - id
      - image
      - offered_by
      - platform
      - prices
      - readable_id
      - resource_content_tags
      - resource_type
      - title
      - topics
      - updated_on
    LearningResourceDepartment:
      type: object
      description: Serializer for LearningResourceDepartment
      properties:
        department_id:
          type: string
          maxLength: 6
        name:
          type: string
          maxLength: 256
      required:
      - department_id
      - name
    LearningResourceImage:
      type: object
      description: Serializer for LearningResourceImage
      properties:
        id:
          type: integer
          readOnly: true
        url:
          type: string
          maxLength: 2048
        description:
          type: string
          nullable: true
          maxLength: 1024
        alt:
          type: string
          nullable: true
          maxLength: 1024
      required:
      - id
    LearningResourceInstructor:
      type: object
      description: Serializer for LearningResourceInstructor model
      properties:
        id:
          type: integer
          readOnly: true
        first_name:
          type: string
          nullable: true
          maxLength: 128
        last_name:
          type: string
          nullable: true
          maxLength: 128
        full_name:
          type: string
          nullable: true
          maxLength: 256
      required:
      - id
    LearningResourceRun:
      type: object
      description: Serializer for the LearningResourceRun model
      properties:
        id:
          type: integer
          readOnly: true
        instructors:
          type: array
          items:
            $ref: '#/components/schemas/LearningResourceInstructor'
          readOnly: true
          nullable: true
        image:
          allOf:
          - $ref: '#/components/schemas/LearningResourceImage'
          readOnly: true
          nullable: true
        run_id:
          type: string
          maxLength: 128
        title:
          type: string
          maxLength: 256
        description:
          type: string
          nullable: true
        full_description:
          type: string
          nullable: true
        last_modified:
          type: string
          format: date-time
          nullable: true
        published:
          type: boolean
        languages:
          type: array
          items:
            type: string
            maxLength: 24
          nullable: true
        url:
          type: string
          format: uri
          nullable: true
          maxLength: 2048
        level:
          type: string
          nullable: true
          maxLength: 128
        slug:
          type: string
          nullable: true
          maxLength: 1024
        availability:
          type: string
          nullable: true
          maxLength: 128
        semester:
          type: string
          nullable: true
          maxLength: 20
        year:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
          nullable: true
        start_date:
          type: string
          format: date-time
          nullable: true
        end_date:
          type: string
          format: date-time
          nullable: true
        enrollment_start:
          type: string
          format: date-time
          nullable: true
        enrollment_end:
          type: string
          format: date-time
          nullable: true
        prices:
          type: array
          items:
            type: string
            format: decimal
            pattern: ^-?\d{0,10}(?:\.\d{0,2})?$
          nullable: true
        learning_resource:
          type: integer
      required:
      - id
      - image
      - instructors
      - learning_resource
      - run_id
      - title
    LearningResourceTopic:
      type: object
      description: Serializer for LearningResourceTopic model
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 128
      required:
      - id
      - name
    PaginatedLearningResourceList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/LearningResource'
    Program:
      type: object
      description: Serializer for the Program model
      properties:
        courses:
          type: array
          items:
            $ref: '#/components/schemas/LearningResourceBase'
          readOnly: true
          nullable: true
      required:
      - courses
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
