import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import React from "react"
import { Container, styled } from "ol-components"
// import ResourceCarousel from "@/page-components/ResourceCarousel/ResourceCarousel"

import Header from "@/page-components/Header/Header"
import Footer from "@/page-components/Footer/Footer"


const PageWrapper = styled.div({
  height: "calc(100vh - 80px)",
  display: "flex",
  flexDirection: "column",
})

const PageWrapperInner = styled.div({
  flex: "1",
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <PageWrapper>
        <Header />
        <PageWrapperInner>
          {/* <Outlet /> */}
        </PageWrapperInner>
        <Footer />
      </PageWrapper>
        {/* <LearningResourceDrawer /> */}
    </html>
  );
}
