# Generated by Django 4.1.10 on 2023-11-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0024_remove_course_extra_course_numbers"),
        ("channels_fields", "0008_alter_fieldchannel_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldchannel",
            name="featured_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learning_resources.learningresource",
            ),
        ),
        migrations.AlterField(
            model_name="fieldlist",
            name="field_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="learning_resources.learningresource",
            ),
        ),
    ]
