# Generated by Django 4.2.14 on 2024-07-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_events", "0002_alter_feeditem_guid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedeventdetail",
            name="event_datetime",
            field=models.DateTimeField(db_index=True),
        ),
    ]
