# Generated by Django 4.2.14 on 2024-08-05 16:59

from django.db import migrations, models


def set_end_datetime(apps, schema_editor):
    """
    Populate existing event end datetimes
    """
    FeedEventDetail = apps.get_model("news_events", "FeedEventDetail")
    FeedEventDetail.objects.update(event_end_datetime=models.F("event_datetime"))


class Migration(migrations.Migration):
    dependencies = [
        ("news_events", "0003_alter_feedeventdetail_event_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedeventdetail",
            name="event_end_datetime",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.RunPython(set_end_datetime, reverse_code=migrations.RunPython.noop),
    ]
