# Generated by Django 4.2.11 on 2024-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources_search", "0003_alter_percolatequery_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="percolatequery",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("search_subscription_type", "search_subscription_type"),
                    ("channel_subscription_type", "channel_subscription_type"),
                ],
                max_length=255,
            ),
        ),
    ]
