# Generated by Django 4.2.11 on 2024-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources_search", "0004_alter_percolatequery_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="percolatequery",
            name="query_string",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
