# Generated by Django 4.1.10 on 2023-11-15 20:58

import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models

import profiles.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("widgets", "0003_alter_widgetinstance_configuration"),
        ("learning_resources", "0025_update_course_number_depts"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldChannel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Channel name can only contain the characters: A-Z, a-z, 0-9, _",  # noqa: E501
                                regex="^[A-Za-z0-9_]+$",
                            )
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "avatar",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        max_length=2083,
                        null=True,
                        upload_to=profiles.utils.avatar_uri,
                    ),
                ),
                (
                    "banner",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        max_length=2083,
                        null=True,
                        upload_to=profiles.utils.banner_uri,
                    ),
                ),
                ("about", models.JSONField(blank=True, null=True)),
                ("ga_tracking_id", models.CharField(blank=True, max_length=24)),
                ("public_description", models.TextField(blank=True, default="")),
                (
                    "featured_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning_resources.learningresource",
                    ),
                ),
                (
                    "widget_list",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_channel",
                        to="widgets.widgetlist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subfield",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("position", models.IntegerField(default=0)),
                (
                    "field_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channels.fieldchannel",
                    ),
                ),
                (
                    "parent_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfields",
                        to="channels.fieldchannel",
                    ),
                ),
            ],
            options={
                "unique_together": {("field_channel", "parent_channel")},
            },
        ),
        migrations.CreateModel(
            name="FieldList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("position", models.IntegerField(default=0)),
                (
                    "field_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lists",
                        to="channels.fieldchannel",
                    ),
                ),
                (
                    "field_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("field_list", "field_channel")},
            },
        ),
        migrations.CreateModel(
            name="FieldChannelGroupRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("moderators", "moderators")], max_length=48
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channels.fieldchannel",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
            ],
            options={
                "unique_together": {("field", "group", "role")},
                "index_together": {("field", "role")},
            },
        ),
    ]
