# Generated by Django 4.2.11 on 2024-04-02 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0003_channel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldchannel",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Channel name can only contain the characters: A-Z, a-z, 0-9, _",  # noqa: E501
                        regex="^[A-Za-z0-9_]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="fieldchannel",
            name="search_filter",
            field=models.CharField(blank=True, default="", max_length=2048),
        ),
        migrations.AlterUniqueTogether(
            name="fieldchannel",
            unique_together={("name", "channel_type")},
        ),
    ]
