# Generated by Django 4.2.11 on 2024-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0004_unique_type_name_combo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldchannel",
            name="configuration",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
