# Generated by Django 2.2.27 on 2022-08-11 12:29

import imagekit.models.fields
from django.db import migrations

import profiles.utils


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0006_description_textfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldchannel",
            name="avatar",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                max_length=2083,
                null=True,
                upload_to=profiles.utils.avatar_uri,
            ),
        ),
        migrations.AlterField(
            model_name="fieldchannel",
            name="banner",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                max_length=2083,
                null=True,
                upload_to=profiles.utils.banner_uri,
            ),
        ),
    ]
