# Generated by Django 4.2.13 on 2024-06-07 17:52

from django.db import migrations, models

from channels.constants import ChannelType


def change_channel_type(apps, schema_editor):
    FieldChannel = apps.get_model("channels", "FieldChannel")
    FieldChannel.objects.filter(channel_type="offeror").update(
        channel_type=ChannelType.unit.name
    )


def revert_channel_type(apps, schema_editor):
    FieldChannel = apps.get_model("channels", "FieldChannel")
    FieldChannel.objects.filter(channel_type=ChannelType.unit.name).update(
        channel_type="offeror"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0006_remove_channel_type_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldchannel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("topic", "Topic"),
                    ("department", "Department"),
                    ("unit", "Unit"),
                    ("pathway", "Pathway"),
                ],
                max_length=100,
            ),
        ),
        migrations.RunPython(change_channel_type, reverse_code=revert_channel_type),
    ]
