# Generated by Django 4.2.13 on 2024-06-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "learning_resources",
            "0054_rename_description_learningresourceofferor_value_prop",
        ),
        ("channels", "0007_alter_channel_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChannelOfferorDetail",
            new_name="ChannelUnitDetail",
        ),
        migrations.AlterField(
            model_name="channelunitdetail",
            name="channel",
            field=models.OneToOneField(
                on_delete=models.deletion.CASCADE,
                primary_key=True,
                related_name="unit_detail",
                serialize=False,
                to="channels.fieldchannel",
            ),
        ),
        migrations.RenameField(
            model_name="channelunitdetail",
            old_name="offeror",
            new_name="unit",
        ),
    ]
