# Generated by Django 4.2.13 on 2024-06-25 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "learning_resources",
            "0054_rename_description_learningresourceofferor_value_prop",
        ),
        ("widgets", "0003_alter_widgetinstance_configuration"),
        ("testimonials", "0004_update_attestation_avatar_make_optional"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("channels", "0008_rename_offerordetail_unitdetail"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FieldChannel",
            new_name="Channel",
        ),
        migrations.RenameModel(
            old_name="FieldChannelGroupRole",
            new_name="ChannelGroupRole",
        ),
    ]
