# Generated by Django 4.2.13 on 2024-06-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0008_rename_offerordetail_unitdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelunitdetail",
            name="channel",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="unit_detail",
                serialize=False,
                to="channels.fieldchannel",
            ),
        ),
    ]
