# Generated by Django 4.2.13 on 2024-06-25 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("widgets", "0003_alter_widgetinstance_configuration"),
        ("channels", "0009_rename_fieldchannelgrouprole_channelgrouprole_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="widget_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channel",
                to="widgets.widgetlist",
            ),
        ),
    ]
