# Generated by Django 4.2.13 on 2024-06-25 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "learning_resources",
            "0054_rename_description_learningresourceofferor_value_prop",
        ),
        ("channels", "0010_alter_channel_widget_list"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FieldList",
            new_name="ChannelList",
        ),
        migrations.RenameModel(
            old_name="Subfield",
            new_name="SubChannel",
        ),
    ]
