# Generated by Django 4.2.14 on 2024-07-16 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0056_alter_learningresource_readable_id"),
        ("channels", "0011_add_topic_detail_related_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelunitdetail",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channel_unit_details",
                to="learning_resources.learningresourceofferor",
            ),
        ),
    ]
