# Generated by Django 4.2.13 on 2024-06-25 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "learning_resources",
            "0054_rename_description_learningresourceofferor_value_prop",
        ),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("channels", "0011_channellist_subchannel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channelgrouprole",
            old_name="field",
            new_name="channel",
        ),
        migrations.RenameField(
            model_name="channellist",
            old_name="field_channel",
            new_name="channel",
        ),
        migrations.RenameField(
            model_name="channellist",
            old_name="field_list",
            new_name="channel_list",
        ),
        migrations.RenameField(
            model_name="subchannel",
            old_name="field_channel",
            new_name="channel",
        ),
        migrations.AlterUniqueTogether(
            name="subchannel",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="subchannel",
            name="parent_channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_channels",
                to="channels.channel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="channelgrouprole",
            unique_together={("channel", "group", "role")},
        ),
        migrations.AlterUniqueTogether(
            name="channellist",
            unique_together={("channel_list", "channel")},
        ),
        migrations.AlterUniqueTogether(
            name="subchannel",
            unique_together={("channel", "parent_channel")},
        ),
        migrations.AlterIndexTogether(
            name="channelgrouprole",
            index_together={("channel", "role")},
        ),
    ]
