# Generated by Django 4.2.14 on 2024-08-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0013_alter_channel_channel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="published",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
