# Generated by Django 4.2.14 on 2024-07-31 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0060_partially_populate_availability"),
        ("channels", "0013_alter_channel_channel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channeldepartmentdetail",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channel_department_details",
                to="learning_resources.learningresourcedepartment",
            ),
        ),
    ]
