# Generated by Django 4.2.14 on 2024-08-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0014_dept_detail_related_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="published",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
