# Generated by Django 4.2.11 on 2024-05-09 20:27

import imagekit.models.fields
from django.db import migrations, models

import testimonials.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("channels", "0005_alter_fieldchannel_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "attestant_name",
                    models.CharField(
                        help_text="The name of the attestant", max_length=200
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="The attestant's title", max_length=255),
                ),
                ("quote", models.TextField(help_text="The testimonial attestation")),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="The datetime to show the testimonial",
                        null=True,
                    ),
                ),
                (
                    "avatar",
                    imagekit.models.fields.ProcessedImageField(
                        help_text="The attestant's avatar",
                        max_length=2083,
                        upload_to=testimonials.utils.avatar_uri,
                    ),
                ),
                (
                    "cover",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        help_text=(
                            "Optional cover image, only used on certain"
                            " views (homepage)"
                        ),
                        max_length=2083,
                        null=True,
                        upload_to=testimonials.utils.cover_uri,
                    ),
                ),
                (
                    "channels",
                    models.ManyToManyField(
                        help_text="Channels that the testimonial belongs to",
                        related_name="+",
                        to="channels.fieldchannel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
