# Generated by Django 4.2.13 on 2024-06-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0002_add_offeror_to_testimonials"),
    ]

    operations = [
        migrations.AddField(
            model_name="attestation",
            name="position",
            field=models.IntegerField(
                default=1, help_text="The position the attestation should occupy"
            ),
        ),
    ]
