# Generated by Django 4.2.13 on 2024-06-20 15:15

import imagekit.models.fields
from django.db import migrations

import testimonials.utils


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0003_add_order_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attestation",
            name="avatar",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                help_text="The attestant's avatar",
                max_length=2083,
                null=True,
                upload_to=testimonials.utils.avatar_uri,
            ),
        ),
    ]
