# Generated by Django 4.2.13 on 2024-06-25 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0004_update_attestation_avatar_make_optional"),
    ]

    operations = []
