# Generated by Django 4.2.13 on 2024-06-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0009_rename_field_to_channel"),
        ("testimonials", "0004_update_attestation_avatar_make_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attestation",
            name="channels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Channels that the testimonial belongs to",
                related_name="+",
                to="channels.channel",
            ),
        ),
    ]
