# Generated by Django 4.2.13 on 2024-06-26 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0005_rename_avatar_attestation_avatar_test"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attestation",
            old_name="avatar_test",
            new_name="avatar",
        ),
    ]
