# Generated by Django 4.1.10 on 2023-08-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="courses",
            field=models.ManyToManyField(
                related_name="programs", to="learning_resources.course"
            ),
        ),
    ]
