# Generated by Django 4.1.10 on 2023-08-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="learningresource",
            unique_together={("platform", "readable_id", "resource_type")},
        ),
    ]
