# Generated by Django 4.1.10 on 2023-08-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0002_alter_learningresource_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresource",
            name="resource_type",
            field=models.CharField(db_index=True, max_length=24),
        ),
    ]
