# Generated by Django 4.1.10 on 2023-08-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0003_alter_learningresource_resource_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresourceimage",
            name="url",
            field=models.TextField(
                blank=True, default="https://placehold.co/300x200", max_length=2048
            ),
            preserve_default=False,
        ),
    ]
