# Generated by Django 4.1.10 on 2023-08-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0004_alter_learningresourceimage_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningresource",
            name="prices",
        ),
    ]
