# Generated by Django 4.1.10 on 2023-08-21 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning_resources", "0005_remove_learningresource_prices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="courses",
        ),
        migrations.AlterField(
            model_name="learningresourceimage",
            name="url",
            field=models.TextField(max_length=2048),
        ),
        migrations.CreateModel(
            name="LearningResourceRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("PROGRAM_COURSES", "Program Courses"),
                            ("LEARNING_PATH_ITEMS", "Learning Path Items"),
                            ("PODCAST_EPISODES", "Podcast Episodes"),
                        ],
                        max_length=19,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="learning_resources.learningresource",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_paths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "learning_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_path",
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="learningresource",
            name="resources",
            field=models.ManyToManyField(
                blank=True,
                through="learning_resources.LearningResourceRelationship",
                to="learning_resources.learningresource",
            ),
        ),
    ]
