# Generated by Django 4.1.10 on 2023-08-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0007_add_editors_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresourcerelationship",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("PROGRAM_COURSES", "Program Courses"),
                    ("LEARNING_PATH_ITEMS", "Learning Path Items"),
                    ("PODCAST_EPISODES", "Podcast Episodes"),
                ],
                default=None,
                max_length=19,
            ),
        ),
    ]
