# Generated by Django 4.1.10 on 2023-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_resources", "0008_alter_relationship_relation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("course", "course"),
                    ("program", "program"),
                    ("learning_path", "learning_path"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
