# Generated by Django 4.1.10 on 2023-09-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0010_contentfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresourcerun",
            name="checksum",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
