# Generated by Django 4.1.10 on 2023-09-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0012_userlists"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("playlist_id", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=256)),
                ("published", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VideoChannel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("channel_id", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=256)),
                ("published", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="learningresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("course", "course"),
                    ("program", "program"),
                    ("learning_path", "learning_path"),
                    ("video", "video"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("duration", models.CharField(blank=True, max_length=11, null=True)),
                ("transcript", models.TextField(blank=True, default="")),
                (
                    "learning_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlaylistVideo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField()),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_videos",
                        to="learning_resources.playlist",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_videos",
                        to="learning_resources.video",
                    ),
                ),
            ],
            options={
                "unique_together": {("playlist", "video")},
            },
        ),
        migrations.AddField(
            model_name="playlist",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to="learning_resources.videochannel",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="videos",
            field=models.ManyToManyField(
                through="learning_resources.PlaylistVideo",
                to="learning_resources.video",
            ),
        ),
    ]
