# Generated by Django 4.1.10 on 2023-09-28 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0013_podcasts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningresource",
            name="offered_by",
        ),
        migrations.AddField(
            model_name="learningresource",
            name="offered_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learning_resources.learningresourceofferor",
            ),
        ),
    ]
