# Generated by Django 4.1.10 on 2023-10-02 16:21

from django.db import migrations, models

from learning_resources.constants import LearningResourceType
from learning_resources.etl import podcast, xpro


def populate_etl_source(apps, schema_editor):
    """
    Populate  etl_source for existing learning resources
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    LearningResource.objects.filter(
        resource_type__in=(
            LearningResourceType.podcast.value,
            LearningResourceType.podcast_episode.value,
        )
    ).update(etl_source=podcast.ETL_SOURCE)
    LearningResource.objects.filter(
        resource_type__in=(
            LearningResourceType.course.value,
            LearningResourceType.program.value,
        )
    ).update(etl_source=xpro.ETL_SOURCE)


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0016_alter_learningresource_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="etl_source",
            field=models.CharField(default="", max_length=12),
        ),
        migrations.RunPython(populate_etl_source, migrations.RunPython.noop),
    ]
