# Generated by Django 4.1.10 on 2023-09-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0017_learningresource_etl_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningresourceplatform",
            name="audience",
        ),
        migrations.AddField(
            model_name="learningresource",
            name="professional",
            field=models.BooleanField(default=False),
        ),
    ]
