# Generated by Django 4.1.10 on 2023-10-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0018_professional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningresource",
            name="department",
        ),
        migrations.AddField(
            model_name="learningresource",
            name="departments",
            field=models.ManyToManyField(
                to="learning_resources.learningresourcedepartment"
            ),
        ),
    ]
