# Generated by Django 4.1.10 on 2023-10-02 16:21

from django.db import migrations

from learning_resources.constants import PlatformType
from learning_resources.etl import ocw


def update_ocw_readable_id(apps, schema_editor):
    """
    Update readable_id and course.extra_course_numbers for existing
    OCW learning resources
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    for resource in (
        LearningResource.objects.filter(platform__platform=PlatformType.ocw.value)
        .select_related("course")
        .prefetch_related("runs")
    ):
        course = resource.course
        course.extra_course_numbers = [course.learning_resource.readable_id] + (
            course.extra_course_numbers or []
        )
        course.save()
        resource.etl_source = ocw.ETL_SOURCE
        run = resource.runs.first()
        resource.readable_id = f"{resource.readable_id}+{run.semester}_{run.year}"
        resource.save()


def revert_ocw_readable_id(apps, schema_editor):
    """
    Revert readable_id and course.extra_course_numbers for existing
    OCW learning resources
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    for resource in LearningResource.objects.filter(
        platform__platform=PlatformType.ocw.value
    ).select_related("course"):
        resource.readable_id = resource.readable_id.split("+")[0]
        resource.save()
        course = resource.course
        course.extra_course_numbers = (
            None
            if course.extra_course_numbers == [resource.readable_id]
            else course.extra_course_numbers[1:]
        )
        course.save()


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0019_departments"),
    ]
    operations = [
        migrations.RunPython(update_ocw_readable_id, revert_ocw_readable_id),
    ]
