# Generated by Django 4.1.10 on 2023-10-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0020_refactor_ocw_readable_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresourceofferor",
            name="code",
            field=models.CharField(default="", max_length=12),
        ),
        migrations.AddField(
            model_name="learningresourceofferor",
            name="professional",
            field=models.BooleanField(default=False),
        ),
    ]
