# Generated by Django 4.1.10 on 2023-10-31 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0023_course_course_numbers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="extra_course_numbers",
        ),
    ]
