# Generated by Django 4.1.10 on 2023-11-20 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0025_update_course_number_depts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learningresourceplatform",
            old_name="platform",
            new_name="code",
        ),
    ]
