# Generated by Django 4.1.10 on 2023-12-08 15:05

from django.db import migrations, models


def assign_new_offeror_foreign_keys(apps, schema_editor):
    """
    Update offeror pk for every resource that has one
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    LearningResourceOfferor = apps.get_model(
        "learning_resources", "LearningResourceOfferor"
    )
    offerors = LearningResourceOfferor.objects.all()
    for lr in LearningResource.objects.filter(offered_by_id__isnull=False):
        new_pk = offerors.filter(id=lr.offered_by_id).first().code
        lr.offered_by_new_id = new_pk
        lr.offered_by = None
        lr.save()


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0027_unique_offeror_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresource",
            name="offered_by",
            field=models.ForeignKey(
                "learningresourceofferor",
                blank=True,
                null=True,
                db_constraint=False,
                on_delete=models.SET_NULL,
            ),
        ),
        migrations.AlterField(
            model_name="learningresourceofferor",
            name="id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="learningresourceofferor",
            name="code",
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="offered_by_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="learning_resources",
                to="learning_resources.learningresourceofferor",
            ),
        ),
        migrations.RunPython(
            assign_new_offeror_foreign_keys, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="learningresource",
            name="offered_by",
        ),
        migrations.RenameField(
            model_name="learningresource",
            old_name="offered_by_new",
            new_name="offered_by",
        ),
        migrations.RemoveField(
            model_name="learningresourceofferor",
            name="id",
        ),
    ]
