# Generated by Django 4.1.10 on 2023-12-08 18:13

from django.db import migrations, models


def assign_new_department_foreign_keys(apps, schema_editor):
    """
    Assign foreign keys to departments by department id
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    LearningResourceDepartment = apps.get_model(
        "learning_resources", "LearningResourceDepartment"
    )
    LearningResourceDepartmentNew = apps.get_model(
        "learning_resources", "LearningResourceDepartmentNew"
    )
    for department in LearningResourceDepartment.objects.all():
        LearningResourceDepartmentNew.objects.create(
            department_id=department.department_id, name=department.name
        )
    for lr in LearningResource.objects.filter(departments__isnull=False):
        new_pks = lr.departments.values_list("department_id", flat=True)
        lr.departments_new.set(new_pks)
        lr.save()


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0028_alter_offeror_pk"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningResourceDepartmentNew",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("department_id", models.CharField(max_length=6, primary_key=True)),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="learningresource",
            name="departments_new",
            field=models.ManyToManyField(
                to="learning_resources.learningresourcedepartmentnew"
            ),
        ),
        migrations.RunPython(
            assign_new_department_foreign_keys, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="learningresource",
            name="departments",
        ),
        migrations.DeleteModel(
            name="LearningResourceDepartment",
        ),
        migrations.RenameField(
            model_name="learningresource",
            old_name="departments_new",
            new_name="departments",
        ),
        migrations.RenameModel(
            "LearningResourceDepartmentNew", "LearningResourceDepartment"
        ),
    ]
