# Generated by Django 4.1.10 on 2023-12-12 17:45

import django.contrib.postgres.fields
from django.db import migrations, models


def level_to_array(apps, schema_editor):
    """
    Convert level from a string to an array
    """
    LearningResourceRun = apps.get_model("learning_resources", "LearningResourceRun")
    for run in LearningResourceRun.objects.filter(level__isnull=False).iterator():
        str_level = ",".join(
            [f'"{val.strip()}"' for val in run.level.split(",") if val.strip()]
        )
        run.level = f"{{{str_level}}}"
        run.save()


def level_to_string(apps, schema_editor):
    """
    Convert level from an array to a string
    """
    LearningResourceRun = apps.get_model("learning_resources", "LearningResourceRun")
    for run in LearningResourceRun.objects.iterator():
        str_level = run.level.replace('"', "").strip("{}")
        run.level = str_level
        run.save()


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0029_alter_department_pk"),
    ]

    operations = [
        migrations.RunPython(level_to_array, reverse_code=level_to_string),
        migrations.AlterField(
            model_name="learningresourcerun",
            name="level",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), size=None, default=[]
            ),
        ),
    ]
