# Generated by Django 4.1.10 on 2023-12-14 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0030_alter_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentfile",
            name="section",
        ),
        migrations.RemoveField(
            model_name="contentfile",
            name="section_slug",
        ),
        migrations.RemoveField(
            model_name="contentfile",
            name="short_url",
        ),
    ]
