# Generated by Django 4.1.10 on 2023-12-14 19:49

from django.db import migrations, models


def assign_tags(apps, schema_editor):
    """
    Convert level from a string to an array
    """
    ContentFile = apps.get_model("learning_resources", "ContentFile")
    LearningResourceContentTag = apps.get_model(
        "learning_resources", "LearningResourceContentTag"
    )
    for cf in (
        ContentFile.objects.exclude(learning_resource_types__isnull=True)
        .only("learning_resource_types")
        .iterator()
    ):
        cf.content_tags.set(
            [
                LearningResourceContentTag.objects.get_or_create(name=tag)[0]
                for tag in cf.learning_resource_types
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0031_remove_contentfile_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learningresource",
            old_name="resource_content_tags",
            new_name="content_tags",
        ),
        migrations.AddField(
            model_name="contentfile",
            name="content_tags",
            field=models.ManyToManyField(
                to="learning_resources.learningresourcecontenttag"
            ),
        ),
        migrations.RunPython(assign_tags, reverse_code=migrations.RunPython.noop),
    ]
