# Generated by Django 4.2.9 on 2024-02-02 00:34
from django.db import migrations


def update_languages_and_level(apps, _schema_editor):
    """
    Convert relative urls to absolute urls
    """
    LearningResourceRun = apps.get_model("learning_resources", "LearningResourceRun")

    # In postgres, arrays {NULL} and {NULL} are equal.
    # Django's arrayfield __contains query use postgres &> and &&, which
    # do not work with null values.
    LearningResourceRun.objects.filter(level=[None]).update(level=[])
    LearningResourceRun.objects.filter(languages=[None]).update(languages=[])


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0036_update_ocw_contentfile_urls"),
    ]

    operations = [
        migrations.RunPython(
            update_languages_and_level, reverse_code=migrations.RunPython.noop
        ),
    ]
