# Generated by Django 4.2.9 on 2024-02-02 00:34
from django.db import migrations

from learning_resources.constants import LevelType
from learning_resources.etl.utils import transform_levels


def alter_values_to_names(apps, _schema_editor):
    """
    Convert LearningResourceRun.level from array of LevelType values to LevelType
    names
    """
    LearningResourceRun = apps.get_model("learning_resources", "LearningResourceRun")

    for run in LearningResourceRun.objects.filter(level__len__gt=0):
        run.level = transform_levels(run.level)
        run.save()


def alter_names_to_values(apps, _schema_editor):
    """
    Convert LearningResourceRun.level from array of LevelType names to LevelType
    values
    """
    LearningResourceRun = apps.get_model("learning_resources", "LearningResourceRun")

    for run in LearningResourceRun.objects.filter(level__len__gt=0):
        run.level = [LevelType[key].value for key in run.level]
        run.save()


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0037_remove_null_levels_langs"),
    ]

    operations = [
        migrations.RunPython(alter_values_to_names, alter_names_to_values),
    ]
