# Generated by Django 4.2.10 on 2024-03-03 00:09

import django.db.models.deletion
from django.db import migrations, models

import learning_resources.utils


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0038_use_keys_for_levels"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramLetterConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "branding",
                    models.ImageField(
                        max_length=2083,
                        null=True,
                        upload_to=learning_resources.utils.program_image_upload_uri,
                    ),
                ),
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_letter_configuration",
                        to="learning_resources.program",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramLetterSignator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=256)),
                (
                    "signature",
                    models.ImageField(
                        max_length=2083,
                        null=True,
                        upload_to=learning_resources.utils.program_signator_signature_image_upload_uri,
                    ),
                ),
                (
                    "letter_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatories",
                        to="learning_resources.programletterconfiguration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
