# Generated by Django 4.2.10 on 2024-02-27 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0038_use_keys_for_levels"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoChannel",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "channel_id",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=256)),
                ("published", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="learningresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("program", "Program"),
                    ("learning_path", "Learning Path"),
                    ("podcast", "Podcast"),
                    ("podcast_episode", "Podcast Episode"),
                    ("video", "Video"),
                    ("video_playlist", "Video Playlist"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="learningresourcerelationship",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("PROGRAM_COURSES", "Program Courses"),
                    ("LEARNING_PATH_ITEMS", "Learning Path Items"),
                    ("PODCAST_EPISODES", "Podcast Episodes"),
                    ("PLAYLIST_VIDEOS", "Playlist Videos"),
                ],
                default=None,
                max_length=19,
            ),
        ),
        migrations.CreateModel(
            name="VideoPlaylist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to="learning_resources.videochannel",
                    ),
                ),
                (
                    "learning_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_playlist",
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("duration", models.CharField(blank=True, max_length=11, null=True)),
                ("transcript", models.TextField(blank=True, default="")),
                (
                    "learning_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
