# Generated by Django 4.2.11 on 2024-04-19 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0039_videos"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningResourceSchool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("url", models.URLField()),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AlterModelOptions(
            name="learningresourcedepartment",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="learningresourcedepartment",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="learning_resources.learningresourceschool",
            ),
        ),
    ]
