# Generated by Django 4.2.11 on 2024-04-22 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0040_add_lrd_view_collection_table"),
        ("learning_resources", "0040_schools"),
    ]

    operations = []
