# Generated by Django 4.2.11 on 2024-04-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "learning_resources",
            "0041_merge_0040_add_lrd_view_collection_table_0040_schools",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresourceviewevent",
            name="learning_resource",
            field=models.ForeignKey(
                editable=False,
                help_text="The learning resource for this event.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="learning_resources.learningresource",
            ),
        ),
    ]
