# Generated by Django 4.2.11 on 2024-04-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0042_update_ondelete_for_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresourcetopic",
            name="subtopics",
            field=models.ManyToManyField(
                blank=True, null=True, to="learning_resources.learningresourcetopic"
            ),
        ),
    ]
