# Generated by Django 4.2.11 on 2024-04-30 17:18

from django.db import migrations, models

from learning_resources.etl.loaders import load_next_start_date


def assign_next_start_date(apps, schema_editor):
    """
    Assign next start dates
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")

    for resource in LearningResource.objects.filter(
        resource_type__in=["course", "program"]
    ).iterator():
        load_next_start_date(resource)


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0042_update_ondelete_for_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="next_start_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="learningresourcerun",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            assign_next_start_date, reverse_code=migrations.RunPython.noop
        ),
    ]
