# Generated by Django 4.2.11 on 2024-04-26 15:35

import django.contrib.postgres.fields
from django.db import migrations, models

from learning_resources.constants import LearningResourceFormat, LearningResourceType


def populate_format(apps, schema_editor):
    """
    Populate format for existing program/course resources
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    LearningResource.objects.filter(
        resource_type__in=(
            LearningResourceType.program.name,
            LearningResourceType.course.name,
        )
    ).update(format=[LearningResourceFormat.online.value])


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0042_update_ondelete_for_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="format",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Online", "Online"),
                        ("Hybrid", "Hybrid"),
                        ("In person", "In person"),
                    ],
                    max_length=24,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(populate_format, reverse_code=migrations.RunPython.noop),
    ]
