# Generated by Django 4.2.11 on 2024-04-30 15:39

import django.contrib.postgres.fields
from django.db import migrations, models

from learning_resources.constants import LearningResourceDelivery, LearningResourceType


def populate_learning_format(apps, schema_editor):
    """
    Populate learning_format for existing program/course resources
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    LearningResource.objects.filter(
        resource_type__in=(
            LearningResourceType.program.name,
            LearningResourceType.course.name,
        )
    ).update(learning_format=[LearningResourceDelivery.online.name])


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0043_learningresource_format"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningresource",
            name="format",
        ),
        migrations.AddField(
            model_name="learningresource",
            name="learning_format",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(db_index=True, max_length=24),
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(
            populate_learning_format, reverse_code=migrations.RunPython.noop
        ),
    ]
