# Generated by Django 4.2.11 on 2024-04-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0044_rename_learningresource_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="next_start_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="learningresourcerun",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
