# Generated by Django 4.2.11 on 2024-05-02 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0043_add_nestable_topics"),
        ("learning_resources", "0044_rename_learningresource_format"),
    ]

    operations = []
