# Generated by Django 4.2.11 on 2024-05-01 19:04

from django.db import migrations, models

from learning_resources.constants import (
    LearningResourceType,
    OfferedBy,
    RunAvailability,
)


def populate_certification(apps, schema_editor):
    """
    Populate certification for existing program/course resources
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    for lr in LearningResource.objects.filter(
        resource_type__in=(
            LearningResourceType.program.name,
            LearningResourceType.course.name,
        )
    ):
        lr.certification = bool(
            lr.professional
            or (
                lr.offered_by
                and lr.offered_by.name == OfferedBy.mitx.value
                and (
                    any(
                        availability != RunAvailability.archived.value
                        for availability in lr.runs.values_list(
                            "availability", flat=True
                        )
                    )
                )
            )
        )
        lr.save()


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0045_learningresource_next_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="certification",
            field=models.BooleanField(default=False),
        ),
    ]
