# Generated by Django 4.2.11 on 2024-05-10 15:12

import django.contrib.postgres.fields

# Generated by Django 4.2.11 on 2024-05-01 19:04
from django.db import migrations, models

from learning_resources.constants import (
    LearningResourceFormat,
    LearningResourceType,
)


def populate_video_podcast_format(apps, schema_editor):
    """
    Populate learning_format for existing  resources
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    LearningResource.objects.exclude(
        resource_type__in=[
            LearningResourceType.course.name,
            LearningResourceType.program.name,
        ]
    ).update(learning_format=[LearningResourceFormat.online.name])


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0047_add_nestable_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresource",
            name="learning_format",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(db_index=True, max_length=24),
                default=["online"],
                size=None,
            ),
        ),
        migrations.RunPython(
            populate_video_podcast_format, reverse_code=migrations.RunPython.noop
        ),
    ]
