# Generated by Django 4.2.11 on 2024-05-15 18:13

import django.contrib.postgres.fields
from django.db import migrations, models

from learning_resources.constants import (
    LearningResourceType,
)
from learning_resources.models import default_delivery


def populate_video_podcast_format(apps, schema_editor):
    """
    Populate learning_format for existing  resources
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    LearningResource.objects.exclude(
        resource_type__in=[
            LearningResourceType.course.name,
            LearningResourceType.program.name,
        ]
    ).update(learning_format=default_delivery())


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0048_null_ocw_start_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresource",
            name="learning_format",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(db_index=True, max_length=24),
                default=default_delivery,
                size=None,
            ),
        ),
        migrations.RunPython(
            populate_video_podcast_format, reverse_code=migrations.RunPython.noop
        ),
    ]
