# Generated by Django 4.2.13 on 2024-05-21 19:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0049_alter_learning_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresourceofferor",
            name="audience",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="learningresourceofferor",
            name="certifications",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="learningresourceofferor",
            name="content_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="learningresourceofferor",
            name="fee",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="learningresourceofferor",
            name="formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="learningresourceofferor",
            name="more_information",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="learningresourceofferor",
            name="offerings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), default=list, size=None
            ),
        ),
    ]
