# Generated by Django 4.2.13 on 2024-05-23 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0050_offeror_details"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningresourceinstructor",
            options={"ordering": ["last_name", "first_name"]},
        ),
    ]
