# Generated by Django 4.2.13 on 2024-05-29 18:36

from django.db import migrations, models

from learning_resources.constants import CertificationType
from learning_resources.etl.constants import ETLSource


def add_certification_type(apps, schema_editor):
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    LearningResource.objects.filter(certification=True, professional=True).update(
        certification_type=CertificationType.professional.name
    )
    LearningResource.objects.filter(certification=True, professional=False).exclude(
        etl_source=ETLSource.micromasters.name
    ).update(certification_type=CertificationType.completion.name)
    LearningResource.objects.filter(
        certification=True, etl_source=ETLSource.micromasters.name
    ).update(certification_type=CertificationType.micromasters.name)


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0051_instructor_sort"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="certification_type",
            field=models.CharField(
                choices=[
                    ("micromasters", "Micromasters Credential"),
                    ("professional", "Professional Certificate"),
                    ("completion", "Certificate of Completion"),
                    ("none", "No Certificate"),
                ],
                default="none",
                max_length=24,
            ),
        ),
        migrations.RunPython(
            add_certification_type, reverse_code=migrations.RunPython.noop
        ),
    ]
