# Generated by Django 4.2.13 on 2024-05-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0051_instructor_sort"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresourceofferor",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
