# Generated by Django 4.2.13 on 2024-05-31 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0052_learningresource_certification_type"),
        ("learning_resources", "0052_learningresourceofferor_description"),
    ]

    operations = []
