# Generated by Django 4.2.13 on 2024-05-31 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0053_merge_20240531_1657"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learningresourceofferor",
            old_name="description",
            new_name="value_prop",
        ),
    ]
