# Generated by Django 4.2.13 on 2024-07-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0055_alter_relationship_options_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresource",
            name="readable_id",
            field=models.CharField(max_length=512),
        ),
    ]
