# Generated by Django 4.2.14 on 2024-07-16 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0056_alter_learningresource_readable_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresourcetopic",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The icon to display for the topic.",
                max_length=128,
            ),
        ),
        migrations.CreateModel(
            name="LearningResourceTopicMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("topic_name", models.CharField(max_length=128)),
                (
                    "offeror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="learning_resources.learningresourceofferor",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="learning_resources.learningresourcetopic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
