# Generated by Django 4.2.14 on 2024-07-23 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0057_add_icon_and_mappings_to_topics"),
        ("learning_resources", "0057_learningresource_next_prices"),
    ]

    operations = []
