# Generated by Django 4.2.15 on 2024-08-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0060_partially_populate_availability"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learningresourcerun",
            old_name="availability",
            new_name="status",
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="delivery",
            field=models.CharField(default="online", max_length=24),
        ),
    ]
