# Generated by Django 4.2.15 on 2024-08-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0060_partially_populate_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="completeness",
            field=models.FloatField(default=1.0),
        ),
    ]
