# Generated by Django 4.2.15 on 2024-08-26 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0061_rename_availability_temporary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learningresource",
            old_name="availability_list",
            new_name="availability",
        ),
        migrations.RemoveField(
            model_name="learningresource",
            name="availability_old",
        ),
    ]
