# Generated by Django 4.2.15 on 2024-08-26 21:39

from django.db import migrations, models


def populate_run_availability(apps, schema_editor):
    """
    Set the default availability of each run to match the availability of the resource
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")

    for resource in LearningResource.objects.prefetch_related("runs").filter(
        published=True, runs__published=True
    ):
        resource.runs.filter(published=True).update(availability=resource.availability)


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0061_learningresourcerun_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresourcerun",
            name="availability",
            field=models.CharField(
                choices=[("dated", "Dated"), ("anytime", "Anytime")],
                max_length=24,
                null=True,
            ),
        ),
        migrations.RunPython(populate_run_availability, migrations.RunPython.noop),
    ]
