# Generated by Django 4.2.15 on 2024-08-26 21:37

import django.contrib.postgres.fields
from django.db import migrations, models

import learning_resources.models
from learning_resources.constants import LearningResourceType


def assign_run_delivery(apps, schema_editor):
    """Assign initial delivery method to all runs based on the parent resource"""
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    for resource in LearningResource.objects.filter(
        resource_type__in=[
            LearningResourceType.course.name,
            LearningResourceType.program.name,
        ],
        published=True,
    ):
        resource.runs.filter(published=True).update(delivery=resource.delivery)


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0063_continuing_ed_credits_cc_license"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningresourcerun",
            name="availability",
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="delivery",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("online", "Online"),
                        ("hybrid", "Hybrid"),
                        ("in_person", "In person"),
                        ("offline", "Offline"),
                    ],
                    db_index=True,
                    max_length=24,
                ),
                default=learning_resources.models.default_delivery,
                size=None,
            ),
        ),
        migrations.RunPython(
            assign_run_delivery,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
