# Generated by Django 4.2.15 on 2024-08-26 21:39

from django.db import migrations, models

from learning_resources.constants import LearningResourceType


def assign_run_availability(apps, schema_editor):
    """Assign initial availability to all runs based on the parent resource"""
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    for resource in LearningResource.objects.filter(
        resource_type__in=[
            LearningResourceType.course.name,
            LearningResourceType.program.name,
        ],
        published=True,
    ):
        resource.runs.filter(published=True).update(availability=resource.availability)


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0064_learningresourcerun_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresourcerun",
            name="availability",
            field=models.CharField(
                choices=[("dated", "Dated"), ("anytime", "Anytime")],
                max_length=24,
                null=True,
            ),
        )
    ]
