# Generated by Django 4.2.16 on 2024-09-23 14:18

import django.contrib.postgres.fields
from django.db import migrations, models

import learning_resources.models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0067_ocw_delivery_online_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="format",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("synchronous", "Synchronous"),
                        ("asynchronous", "Asynchronous"),
                    ],
                    max_length=24,
                ),
                default=learning_resources.models.default_format,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="pace",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("self_paced", "Self-paced"),
                        ("instructor_paced", "Instructor-paced"),
                    ],
                    max_length=24,
                ),
                default=learning_resources.models.default_pace,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="format",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("synchronous", "Synchronous"),
                        ("asynchronous", "Asynchronous"),
                    ],
                    max_length=24,
                ),
                default=learning_resources.models.default_format,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="pace",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("self_paced", "Self-paced"),
                        ("instructor_paced", "Instructor-paced"),
                    ],
                    max_length=24,
                ),
                default=learning_resources.models.default_pace,
                size=None,
            ),
        ),
    ]
