name: E2E Testing
on: [push]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18.18.2"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build frontend
        run: MITOPEN_HOSTNAME=nginx:8063 yarn build

      - name: Build services
        run: docker compose -f docker-compose-e2e-tests.yml build

      - name: Start services
        run: docker compose -f docker-compose-e2e-tests.yml up nginx web db --detach --wait

      - name: Apply test data
        run: ./e2e_testing/scripts/apply-fixtures.sh

      - name: Run E2E tests
        run: docker compose -f docker-compose-e2e-tests.yml run e2e-tests
