name: E2E Testing
on: [push]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run web service and E2E tests
        run: docker compose -f docker-compose-e2e-tests.yml up --exit-code-from e2e-tests
