name: E2E Testing
on: [push]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18.18.2"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build frontend
        run: MITOPEN_HOSTNAME=nginx:8063 yarn build

      - name: Run services and E2E tests
        run: |
          docker compose -f docker-compose-e2e-tests.yml build
          docker compose -f docker-compose-e2e-tests.yml up nginx web db --detach --wait
          docker compose -f docker-compose-e2e-tests.yml cp e2e_testing/fixtures/002_carousel.sql db:/002_carousel.sql
          docker compose -f docker-compose-e2e-tests.yml exec -u postgres db psql postgres postgres -f /002_carousel.sql
          docker compose -f docker-compose-e2e-tests.yml run e2e-tests
          docker compose -f docker-compose-e2e-tests.yml down
