name: E2E Testing
on: [push]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run web service and E2E tests
        run: |
          cp .env.ci .env
          docker compose up e2e-tests
          docker compose down
