name: Release Candidate Deploy

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [release-candidate]
  workflow_dispatch: # manual trigger

jobs:
  # runs if CI workflow was successful OR if this was manually triggered
  on-success:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release-candidate

      - uses: actions/setup-node@v4
        with:
          node-version: "18.18.2"
          cache: yarn
          cache-dependency-path: frontends/yarn.lock

      - name: Setup environment
        run: sudo apt-get install libelf1

      - name: Install frontend dependencies
        working-directory: frontends
        run: yarn install --immutable

      - name: Build frontend
        working-directory: frontends
        run: yarn run build

      - uses: akhileshns/heroku-deploy@581dd286c962b6972d427fcf8980f60755c15520
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "mitopen-rc"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: release-candidate
  # runs ONLY on a failure of the CI workflow
  on-failure:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'failure'
    steps:
      - run: echo 'The triggering workflow failed'
