name: Test RC Deploy

on:
  push:
    branches:
      - "jk/frontend-dev-server"
  workflow_dispatch:

jobs:
  deploy-rc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: jk/frontend-dev-server

      - uses: akhileshns/heroku-deploy@581dd286c962b6972d427fcf8980f60755c15520
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "mitopen-rc"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: jk/frontend-dev-server
